version: "3.8"
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
     container_name: basketdb
     restart: always
     ports: 
       - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identiydb
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password2020
  orderdb:
    container_name: orderdb
    restart: always
    ports: 
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password2020
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog_api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQURL:rabbitmq
      - IdentityServer:http://identityserver.api:5000
      - DatabaseSettings:ConnectionStrings=mongodb://catalogdb:27017
    ports:
      - "5001:80"
    depends_on:
      - catalogdb
  identityserver_api:
    container_name: identityserver_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb;Database=IdentityDB;Integrated Security=true;"
    ports:
      - "5000:80"
    depends_on:
      - identiydb
  basket_api:
   container_name: basket_api
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - RabbitMQURL:rabbitmq
     - IdentityServer:http://identityserver.api:5000
     - RedisSettings:Port=6379
     - RedisSettings:Host=basketdb
   ports:
     - "5003:80"
   depends_on:
     - basketdb
  stock_api:
   container_name: stock_api
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - IdentityServer:http://identityserver.api:5000
   ports:
     - "5002:80"
   volumes:
    -type: bind
    -source: D:\MicroserviceStockImages
    -target: /app/wwwroot/images
  discount_api:
   container_name: discount_api
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - IdentityServer:http://identityserver.api:5000
     - ConnectionStrings:PostgreSql="Server=discountdb;Port=5432;Database=postgres;User Id=postgres;Password=root;Integrated Security=true;Pooling=true;"
   ports:
     - "5004:80"
   depends_on:
     - discountdb
  payment_api:
   container_name: payment_api
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - IdentityServer:http://identityserver.api:5000
     - RabbitMQURL:rabbitmq
   ports:
     - "5006:80"
  order_api:
   container_name: order_api
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - IdentityServer:http://identityserver.api:5000
     - RabbitMQURL:rabbitmq
   ports:
     - "5005:80"