version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.9.10-management
  catalog_api:
    image: catalog_image
    build:
      context: .
      dockerfile: Services/Catalog/DotnetMicroserviceArchitecture.CatalogAPI/Dockerfile
  identityserver_api:
    image: identityserver_image
    build:
      context: .
      dockerfile: IdentityServer/DotnetMicroserviceArchitecture.IdentityServer/Dockerfile
  basket_api:
    image: basket_image
    build:
      context: .
      dockerfile: Services/Basket/DotnetMicroserviceArchitecture.BasketAPI/Dockerfile
  stock_api:
    image: stock_image
    build:
      context: .
      dockerfile: Services/Stock/DotnetMicroserviceArchitecture.StockAPI/Dockerfile
  discount_api:
    image: discount_image
    build:
      context: .
      dockerfile: Services/Discount/DotnetMicroserviceArchitecture.DiscountAPI/Dockerfile
  payment_api:
    image: payment_image
    build:
      context: .
      dockerfile: Services/Payment/DotnetMicroserviceArchitecture.PaymentAPI/Dockerfile
  order_api:
    image: order_image
    build:
      context: .
      dockerfile: Services/Order/DotnetMicroserviceArchitecture.OrderAPI/Dockerfile
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:

