version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.9.10-management
  catalog_api:
    image: catalog_image
    build:
      context: .
      dockerfile: Services/Catalog/DotnetMicroserviceArchitecture.CatalogAPI/Dockerfile
  identityserver_api:
    image: identityserver_image
    build:
      context: .
      dockerfile: IdentityServer/DotnetMicroserviceArchitecture.IdentityServer/Dockerfile
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:

